version: "3.9"

services:

  app:
    build: .
    container_name: truelysell-php
    volumes:
      - .:/var/www
    networks:
      - truelysell-network

  nginx:
    image: nginx:latest
    container_name: truelysell-nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www     
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - truelysell-network

  mysql:
    image: mysql:8
    container_name: truelysell-mysql
    restart: always
    environment:
      MYSQL_DATABASE: truelysell
      MYSQL_USER: truelyselluser
      MYSQL_PASSWORD: StrongPassword123
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - truelysell-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: truelysell-phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - mysql
    networks:
      - truelysell-network

networks:
  truelysell-network:

volumes:
  mysql-data:
